# Generated by Django 5.1.4 on 2024-12-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=1111, max_length=50),
        ),
    ]
